In [ ]:
import numpy as np
print(np.__version__)
'''NP is basically used to worK
    with ARRAYS    '''

1.26.4


In [47]:
#creating arrays
lst=[1,2,5,7,3,45,23,78,45]#1-D array
lst1=np.array(lst)
lst2= np.array([(1,2,3),(4,5,6)])
print("1 , 0 ,EYE\n")
print(np.zeros(3),'')
print(np.ones(3),'\n')
print(np.eye(3),'\n')

1 , 0 ,EYE

[0. 0. 0.] 
[1. 1. 1.] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [24]:
print('CREATION TOOLS')
np.linspace(0,5,100)             #linspace(start, element ,end)
np.arange(0,10,3)                #arange (start, end ,gap)
np.full((2,3),7)                 #creates 2X3 FULL of 7
np.random.rand(4,5)              #4 X 5 b\w 0-1
np.random.rand(4,5)*100          #4X5 b/w 0-100
np.random.randint(5,size=(4,4))  #int val B\W 0-(N-1)


CREATION TOOLS


array([[1, 1, 0, 0],
       [0, 2, 1, 2],
       [4, 4, 2, 3],
       [0, 2, 4, 2]])

In [41]:
print("PROPERTIES")
lst1.size       #no of elements
lst2.shape      #dimension of arr
lst1.dtype      #data type of arr

lst2.astype(float) #convert data type
lst2.tolist()       #convert to list

PROPERTIES


[[1, 2, 3], [4, 5, 6]]

In [ ]:
'''SORTING  RESHAPING'''
lst1.sort()
lst2.sort(axis=1)

lst2.flatten()    #convet 2-D into 1-D
lst2.T            #gives the transpose no bractekt req
# lst1.size
lst1.reshape(3,3) #reshape 1-D to 2-D (no of ele should match)

In [69]:
'''ADDING REMOVING SPLITING'''
np.append(lst1,values=[23,34])
np.insert(lst2,5,values=[23,34])

np.delete(lst1,2,axis=0)        #delete(name ,index,axis=0/1)
np.delete(lst1,2,axis=1)        #axis=0'rows';axis=1'column'

a=np.split(lst1,3)        #split into 3 sub arrays
np.hsplit(lst2,1)       #split horizontally on 4th index

[array([[1, 2, 3],
        [4, 5, 6]])]

In [91]:
'''SCALLER MATH'''
np.add(lst1,12)     #add +12 to each element
# same work with substract,multiply,divide,power

'''VECTOR MATH'''
np.add(lst1,lst3)  #element wise addition  
# same work with substract,multiply,divide,power

'''SCIENTIFIC MATH'''
np.sqrt(lst1)
# work same with sin,log,abs,ceill,floor,round

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.64575131, 4.79583152],
       [6.70820393, 6.70820393, 8.83176087]])